---
- name: RAN Antenna Settings Adjustment (Capture Full Entry)
  hosts: all
  sources:
    - name: kafka_ran_logs
      ansible.eda.kafka:
        host: service1
        port: 9092
        topic: ai-ran-logs

  rules:
    - name: Print entire event for inspection
      # A simple condition that will always trigger, or just trigger on any event
      condition: event is not none
      action:
        ansible.eda.debug:
          msg: "Received Event: {{ event | to_nice_json }}"