kind: Deployment
apiVersion: apps/v1
metadata:
  name: llamastack-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llamastack
  template:
    metadata:
      labels:
        app: llamastack
      # uncomment if running otel-collector sidecar for trace collection
      # see ../observability/README.md for how to run otel-collector
      #annotations:
      #  sidecar.opentelemetry.io/inject: llamastack-otelsidecar # <- be sure to add this annotation to the **template.metadata**
    spec:
      volumes:
        - name: run-config-volume
          configMap:
            name: run-config
            defaultMode: 420
        - name: llama-persist
          persistentVolumeClaim:
            claimName: llama-persist
        - name: cache
          emptyDir: {}
        - name: pythain
          emptyDir: {}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: llamastack
          env:
            # uncomment if running otel-collector sidecar for trace collection
            #- name: TELEMETRY_SINKS
            #  value: 'console, sqlite, otel_trace'
            #- name: OTEL_TRACE_ENDPOINT
            #  value: http://localhost:4318/v1/traces
            - name: MAX_TOKENS
              value: '128000'
            - name: VLLM_MAX_TOKENS
              value: '128000'
            - name: LLAMA3B_URL
              value: 'https://llama-3-2-3b-maas-apicast-production.apps.prod.rhoai.rh-aiservices-bu.com/v1'
            - name: LLAMA3B_MODEL
              value: llama-3-2-3b
            - name: LLAMA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-secret
                  key: llama-token
            - name: VLLM_API_TOKEN
              value: fake
            - name: CUSTOM_TIKTOKEN_CACHE_DIR
              value: /app/cache
            - name: MILVUS_DB_PATH
              value: milvus.db
            - name: LLAMA_STACK_LOGGING
              value: all=debug
          ports:
            - containerPort: 8321
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: pythain
              mountPath: /pythainlp-data
            - name: run-config-volume
              mountPath: /app-config
            - name: llama-persist
              mountPath: /.llama
            - name: cache
              mountPath: /.cache
          terminationMessagePolicy: File
          image: 'quay.io/redhat-et/llama:vllm-0.2.7'
          args:
            - '--config'
            - /app-config/config.yaml
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600