---
- name: Create Job Template Dynamically from Playbook
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # path to your remediation playbook in the Git repo
    playbook_path: "{{ input_playbook_path | default('./lightspeed-response.yml') }}"

  tasks:
    - name: Load playbook content from variable
      set_fact:
        playbook_data: "{{ lightspeed_playbook | from_yaml }}"

    - name: Extract playbook name
      set_fact:
        dynamic_name: "{{ playbook_data[0].name | default('Unnamed Remediation') }}"

    - name: Create Job Template
      ansible.controller.job_template:
        name: "{{ dynamic_name }}"
        job_type: "run"
        inventory: "{{ input_inventory | default('lab-inventory') }}"
        project: "{{ input_project | default('Lightspeed-Playbooks') }}"
        playbook: "{{ input_playbook | default('lightspeed-response.yml') }}"
        credential: "{{ input_credential | default('lab-credential') }}"
        validate_certs: true
        execution_environment: "Default execution environment"
        become_enabled: true
        ask_limit_on_launch: true