---
- name: Send logs to Slack on HTTP failure
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    slack_token: ""

  tasks:
    - name: Fail if required variables are not set
      ansible.builtin.fail:
        msg: "Slack Instance must be set!"
      when: slack_token | default('') | trim == ''

    - name: Set systemd facts
      ansible.builtin.set_fact:
        linux_service: "{{ input_linux_service | default('httpd') }}"



    - name: Send RCA insights from RHEL AI to Mattermost
      community.general.slack:
        token: "{{ slack_token }}"
        attachments:
          - text: "!!!!!! RCA INSIGHT !!!!!!"
            color: "#ffa500"
            title: "{{ linux_service | capitalize }} Root Cause Identified"
            fields:
              - title: RCA of {{ linux_service | capitalize }} error detected
                value: "AI-Generated Explanation"
                short: true
              - title: Details
                value: "{{ rca_response | default('No RCA available') }}"
                short: true
      
     

    
